services:
  - type: web
    name: fittrack-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: JWT
        sync: false
      - key: CLIENT_URL
        sync: false